src/objects/Disbursement__c.object
<CustomObject>
    <fields>
        <fullName>Funding_Request__c</fullName>
        <description>Relationship to the Funding Request.</description>
        <label>Funding Request</label>
        <referenceTo>Funding_Request__c</referenceTo>
        <relationshipLabel>Disbursements</relationshipLabel>
        <relationshipName>Disbursements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Disbursement</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Funding_Program__c.object
<CustomObject>
    <label>Funding Program</label>
    <nameField>
        <label>Funding Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Funding_Request__c.object
<CustomObject>
    <description>Record of request for outbound financial funding - can be used for both internal and external purposes.</description>
    <fields>
        <fullName>Applying_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Applying Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Funding Requests</relationshipLabel>
        <relationshipName>Funding_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Funding_Program__c</fullName>
        <description>Lookup to the funding program from which funds are being requested.</description>
        <label>Funding Program</label>
        <referenceTo>Funding_Program__c</referenceTo>
        <relationshipLabel>Funding Requests</relationshipLabel>
        <relationshipName>Funding_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Funding Request</label>
    <nameField>
        <label>Funding Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Request__c/fields/FundingProgram__c.field-meta.xml
<CustomField>
    <fullName>FundingProgram__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the funding program from which funds are being requested.</description>
    <label>Funding Program</label>
    <referenceTo>Funding_Program__c</referenceTo>
    <relationshipLabel>Funding Requests</relationshipLabel>
    <relationshipName>FundingRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

src/classes/disbursementsCreateController_TEST.cls
@isTest
private class disbursementsCreateController_TEST {

    @testSetup
    static void setupTestData() {
        Contact contact1 = new Contact(
            FirstName = 'Test',
            LastName = 'Testers'
        );

        insert contact1;

        Funding_Program__c prog1 = new Funding_Program__c(
            Name = 'Test Program'
        );

        insert prog1;

        Funding_Request__c req1 = new Funding_Request__c(
            Name = 'Test Request',
            FundingProgram__c = prog1.Id,
            Applying_Contact__c = contact1.Id
        );

        insert req1;

    }

    @isTest
    static void testGetFundRequest() {
        Funding_Request__c loadReq = [
            SELECT Id
            FROM Funding_Request__c
            WHERE Name = 'Test Request'
            LIMIT 1
        ];

        test.startTest();
        disbursementsCreateController.Request req  = disbursementsCreateController.getFundRequest(loadReq.Id);
        test.stopTest();

        System.assertEquals(req.recordId, loadReq.Id );
        System.assertEquals(req.contactName, 'Test Testers' );

    }

    @isTest
    static void testSaveDisbursements() {
        Funding_Request__c loadReq = [
            SELECT Id
            FROM Funding_Request__c
            WHERE Name = 'Test Request'
            LIMIT 1
        ];

        List<disbursementsCreateController.Disbursement> disps = new List<disbursementsCreateController.Disbursement>();
        Date today = Date.today();
        for (Integer i = 0; i < 4 ; i++) {
            disbursementsCreateController.Disbursement d = new disbursementsCreateController.Disbursement();
            d.amount = 300;
            d.requestId = loadReq.Id;
            d.scheduleDate = today.addMonths(i);
            d.status = 'scheduled';
            disps.add(d);
        }


        test.startTest();
        disbursementsCreateController.saveDisbursements(JSON.serialize(disps));
        test.stopTest();

        Disbursement__c[] disbursements = [
            SELECT Id, Funding_Request__c
            FROM Disbursement__c
            WHERE Funding_Request__c =: loadReq.Id
        ];

        System.assertEquals(disbursements.size(),disps.size());

    }
}