src/objects/Funding_Program__c.object
<CustomObject>
    <label>Funding Program</label>
    <nameField>
        <label>Funding Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Funding_Request__c.object
<CustomObject>
    <description>Record of request for outbound financial funding - can be used for both internal and external purposes.</description>
    <fields>
        <fullName>Applying_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Applying Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Funding Requests</relationshipLabel>
        <relationshipName>Funding_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Applying_Organization__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Applying Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Funding Requests</relationshipLabel>
        <relationshipName>Funding_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Awarded_Amount__c</fullName>
        <label>Awarded Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Funding_Program__c</fullName>
        <description>Lookup to the funding program from which funds are being requested.</description>
        <label>Funding Program</label>
        <referenceTo>Funding_Program__c</referenceTo>
        <relationshipLabel>Funding Requests</relationshipLabel>
        <relationshipName>Funding_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Requested_Amount__c</fullName>
        <label>Requested Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Disbursed__c</fullName>
        <label>Total Disbursed</label>
        <summarizedField>Disbursement__c.Amount__c</summarizedField>
        <summaryFilterItems>
            <field>Disbursement__c.Status__c</field>
            <operation>equals</operation>
            <value>Paid</value>
        </summaryFilterItems>
        <summaryForeignKey>Disbursement__c.Funding_Request__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Remaining__c</fullName>
        <description>Amount remaining to be disbursed or cancelled.</description>
        <formula>Awarded_Amount__c - Total_Disbursed__c -  Total_Cancelled__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Remaining</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Funding Request</label>
    <nameField>
        <label>Funding Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Funding_Request__c/fields/FundingProgram__c.field-meta.xml
<CustomField>
    <fullName>FundingProgram__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the funding program from which funds are being requested.</description>
    <label>Funding Program</label>
    <referenceTo>Funding_Program__c</referenceTo>
    <relationshipLabel>Funding Requests</relationshipLabel>
    <relationshipName>FundingRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/selectors/tests/FundingRequestSelector_TEST.cls
@isTest
public with sharing class FundingRequestSelector_TEST {
    private static TestUser.MinimalAccessPersona minimalAccessPersona = new TestUser.MinimalAccessPersona();

    @TestSetup
    public static void testSetup() {
        TestUser.insertPersonasInTestSetup(
            new List<TestUser.Persona>{ FundingRequestSelector_TEST.minimalAccessPersona }
        );

        Account account = new Account();
        account.Name = 'Test Account';
        insert account;

        Contact contact = new Contact();
        contact.FirstName = 'Test';
        contact.LastName = 'Applicant';
        contact.AccountId = account.Id;
        insert contact;

        Funding_Program__c fundingProgram = new Funding_Program__c();
        fundingProgram.Name = 'Test Funding Program';
        insert fundingProgram;

        Funding_Request__c fundingRequest = new Funding_Request__c();
        fundingRequest.Name = 'Test funding Request';
        fundingRequest.FundingProgram__c = fundingProgram.Id;
        fundingRequest.Requested_Amount__c = 2000;
        fundingRequest.Applying_Contact__c = contact.Id;
        fundingRequest.Applying_Organization__c = account.Id;
        insert fundingRequest;
    }

    @isTest
    public static void getFundingRequestById() {
        String fundingRequestId = [SELECT Id FROM Funding_Request__c LIMIT 1].Id;

        test.startTest();

        FundingRequestSelector fundingRequestSelector = new FundingRequestSelector();
        List<Funding_Request__c> fundingRequests = fundingRequestSelector.getFundingRequestById(
            fundingRequestId
        );

        test.stopTest();

        system.assertNotEquals(
            null,
            fundingRequests,
            'fundingRequests should have at least one funding request record'
        );
    }

    @isTest
    public static void callFundingRequestWithNoId() {
        test.startTest();

        FundingRequestSelector fundingRequestSelector = new FundingRequestSelector();
        List<Funding_Request__c> fundingRequests = fundingRequestSelector.getFundingRequestById(
            null
        );

        test.stopTest();

        system.assertEquals(
            new List<Funding_Request__c>(),
            fundingRequests,
            'fundingRequests should return an empty list'
        );
    }

    @isTest
    private static void callFundingRequest_MissingCrud() {
        // Configure permissions.
        FundingRequestSelector_TEST.minimalAccessPersona.load();
        Test.startTest();

        System.QueryException actualException;

        System.runAs(FundingRequestSelector_TEST.minimalAccessPersona.getUser()) {
            System.assertEquals(
                false,
                Schema.Funding_Request__c.SObjectType.getDescribe().isAccessible()
            );

            System.assertEquals(
                false,
                Schema.Contact.SObjectType.getDescribe().isAccessible()
            );

            System.assertEquals(
                false,
                Schema.Funding_Request__c.SObjectType.fields.Requested_Amount__c.getDescribe()
                    .isAccessible()
            );

            System.assertEquals(
                false,
                Schema.Funding_Request__c.SObjectType.fields.Awarded_Amount__c.getDescribe()
                    .isAccessible()
            );

            System.assertEquals(
                false,
                Schema.Funding_Request__c.SObjectType.fields.Total_Disbursed__c.getDescribe()
                    .isAccessible()
            );

            System.assertEquals(
                false,
                Schema.Funding_Request__c.SObjectType.fields.Total_Remaining__c.getDescribe()
                    .isAccessible()
            );

            System.assertEquals(
                false,
                Schema.Funding_Request__c.SObjectType.fields.Total_Remaining__c.getDescribe()
                    .isAccessible()
            );
            // Question regarding lookups

            // Run the test
            String fundingRequestId = [SELECT Id FROM Funding_Request__c LIMIT 1].Id;

            final FundingRequestSelector fundingRequestSelector = new FundingRequestSelector();

            try {
                List<Funding_Request__c> fundingRequests = fundingRequestSelector.getFundingRequestById(
                    fundingRequestId
                );
            } catch (System.QueryException e) {
                actualException = e;
            }
        }

        Test.stopTest();

        System.assertNotEquals(
            null,
            actualException,
            'A System.QueryException should have been thrown because the user cannot read Funding_Request__c.'
        );
    }

    @isTest
    private static void callFundingRequest_WithCrudAccess() {
        Test.startTest();

        System.assert(Schema.Funding_Request__c.SObjectType.getDescribe().isAccessible());

        System.assert(Schema.Contact.SObjectType.getDescribe().isAccessible());

        System.assert(
            Schema.Funding_Request__c.SObjectType.fields.Requested_Amount__c.getDescribe()
                .isAccessible()
        );

        System.assert(
            Schema.Funding_Request__c.SObjectType.fields.Awarded_Amount__c.getDescribe()
                .isAccessible()
        );

        System.assert(
            Schema.Funding_Request__c.SObjectType.fields.Total_Disbursed__c.getDescribe()
                .isAccessible()
        );

        System.assert(
            Schema.Funding_Request__c.SObjectType.fields.Total_Remaining__c.getDescribe()
                .isAccessible()
        );

        System.assert(
            Schema.Funding_Request__c.SObjectType.fields.Total_Remaining__c.getDescribe()
                .isAccessible()
        );

        // Run the test
        String fundingRequestId = [SELECT Id FROM Funding_Request__c LIMIT 1].Id;

        final FundingRequestSelector fundingRequestSelector = new FundingRequestSelector();

        List<Funding_Request__c> fundingRequests = fundingRequestSelector.getFundingRequestById(
            fundingRequestId
        );

        Test.stopTest();

        System.assertNotEquals(
            null,
            fundingRequests.isEmpty(),
            'Funding Request should not be empty'
        );

        System.assertEquals(
            1,
            fundingRequests.size(),
            'Funding Request list should bring one record'
        );

        System.assertEquals(fundingRequestId, fundingRequests[0].Id);
        System.assertEquals(2000, fundingRequests[0].Requested_Amount__c);
    }
}